{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "adad6431",
   "metadata": {},
   "source": [
    "# HPCL RTI Analytics — Notebook 1: Data Generation\n",
    "## Decoding a Decade: RTI Filing Pattern Analysis at HPCL (2014–2024)\n",
    "\n",
    "**Project Context**\n",
    "During an internship in the RTI Department at Hindustan Petroleum Corporation Limited (HPCL),\n",
    "the objective was to analyse 10 years of RTI filings to help the department identify patterns,\n",
    "improve compliance, and increase transparency through proactive disclosures.\n",
    "\n",
    "**This Notebook**\n",
    "Generates a realistic synthetic dataset of ~6,000 RTI records across HPCL's departments (2014–2024).\n",
    "Every distribution, seasonal pattern, and departmental characteristic is modelled on how RTI\n",
    "filings actually behave in large Indian PSUs.\n",
    "\n",
    "---\n",
    "\n",
    "### Dataset Schema\n",
    "\n",
    "| Column | Description |\n",
    "|--------|-------------|\n",
    "| `RTI_ID` | Unique identifier (HPCL-RTI-XXXXX) |\n",
    "| `Filing_Date` | Date RTI was filed |\n",
    "| `Year / Month / Quarter` | Derived temporal features |\n",
    "| `Department` | HPCL department receiving the RTI |\n",
    "| `Category` | Type of information sought |\n",
    "| `Applicant_Type` | Individual / Journalist / NGO / Lawyer / Business |\n",
    "| `State` | State from which the RTI was filed |\n",
    "| `Mode_of_Filing` | Online (RTI Portal) / Offline / By Post |\n",
    "| `PIO_Assigned` | Public Information Officer handling the RTI |\n",
    "| `Response_Date` | Date HPCL responded |\n",
    "| `Response_Time_Days` | Days taken to respond |\n",
    "| `Response_Status` | On-Time / Delayed / Significantly Delayed / Pending |\n",
    "| `Disposal_Type` | Info Provided / Partially Provided / Rejected / Transferred |\n",
    "| `Rejection_Reason` | RTI Act Section cited for rejection (if rejected) |\n",
    "| `First_Appeal_Filed` | Whether applicant filed a First Appeal |\n",
    "| `First_Appeal_Outcome` | Upheld / Partially Upheld / Rejected |\n",
    "| `Second_Appeal_CIC` | Whether escalated to Central Information Commission |\n",
    "| `Second_Appeal_Outcome` | CIC ruling |\n",
    "| `Is_Repeat_Filer` | Whether the applicant has filed before |"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "9cb1d9d3",
   "metadata": {},
   "source": [
    "## 1. Imports & Configuration"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0dc34d3e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from datetime import datetime, timedelta\n",
    "import random\n",
    "\n",
    "np.random.seed(42)\n",
    "random.seed(42)\n",
    "print(\"Libraries loaded.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "92536d3b",
   "metadata": {},
   "source": [
    "## 2. HPCL-Specific Configuration\n",
    "All departments, categories, and distributions are modelled on HPCL's actual organisational structure."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6f357131",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Departments with filing-share weights ──────────────────────\n",
    "departments = {\n",
    "    'HR & Personnel':                0.20,\n",
    "    'LPG Division (Indane)':         0.15,\n",
    "    'Finance & Accounts':            0.13,\n",
    "    'Retail Marketing':              0.12,\n",
    "    'Procurement & Materials':       0.08,\n",
    "    'Projects & Pipelines':          0.08,\n",
    "    'Mumbai Refinery':               0.07,\n",
    "    'Vizag Refinery':                0.06,\n",
    "    'Health, Safety & Environment':  0.04,\n",
    "    'Vigilance':                     0.03,\n",
    "    'Legal & Secretarial':           0.02,\n",
    "    'Corporate Planning & BD':       0.01,\n",
    "    'Information Technology':        0.01,\n",
    "}\n",
    "\n",
    "# ── Department → realistic RTI categories ──────────────────────\n",
    "dept_category_map = {\n",
    "    'HR & Personnel': [\n",
    "        'Employee Records & Service Matters', 'Recruitment & Selection',\n",
    "        'Promotion & Transfer Details', 'Pension & Retirement Benefits',\n",
    "        'Salary & Pay Details', 'Policy & Service Rules',\n",
    "    ],\n",
    "    'LPG Division (Indane)': [\n",
    "        'LPG Distributorship Allotment', 'LPG Connection & Cylinder Allocation',\n",
    "        'Dealer/Distributor Grievances', 'LPG Subsidy & Pricing', 'Policy & Service Rules',\n",
    "    ],\n",
    "    'Finance & Accounts': [\n",
    "        'Financial Statements & Budgets', 'Expenditure Details',\n",
    "        'Audit Reports & Observations', 'Salary & Pay Details', 'Policy & Service Rules',\n",
    "    ],\n",
    "    'Retail Marketing': [\n",
    "        'Petrol Pump Dealership Allotment', 'Dealer/Distributor Grievances',\n",
    "        'Tender & Contract Details', 'Fuel Pricing & Policy', 'Policy & Service Rules',\n",
    "    ],\n",
    "    'Procurement & Materials': [\n",
    "        'Tender & Contract Details', 'Vendor Empanelment',\n",
    "        'Expenditure Details', 'Policy & Service Rules',\n",
    "    ],\n",
    "    'Projects & Pipelines': [\n",
    "        'Project Status & Timelines', 'Tender & Contract Details',\n",
    "        'Land Acquisition & Compensation', 'Expenditure Details', 'Environmental Compliance',\n",
    "    ],\n",
    "    'Mumbai Refinery': [\n",
    "        'Refinery Operations & Output', 'Environmental Compliance',\n",
    "        'Incident/Accident Reports', 'Employee Records & Service Matters', 'Tender & Contract Details',\n",
    "    ],\n",
    "    'Vizag Refinery': [\n",
    "        'Refinery Operations & Output', 'Environmental Compliance',\n",
    "        'Incident/Accident Reports', 'Employee Records & Service Matters', 'Tender & Contract Details',\n",
    "    ],\n",
    "    'Health, Safety & Environment': [\n",
    "        'Environmental Compliance', 'Incident/Accident Reports',\n",
    "        'HSE Policy & Standards', 'Pollution Control Data',\n",
    "    ],\n",
    "    'Vigilance':              ['Vigilance & Investigation Matters', 'Complaint Status & Outcome', 'Policy & Service Rules'],\n",
    "    'Legal & Secretarial':    ['Legal Cases & Court Orders', 'Policy & Service Rules', 'Shareholder Information'],\n",
    "    'Corporate Planning & BD':['Financial Statements & Budgets', 'Corporate Strategy Documents', 'Policy & Service Rules'],\n",
    "    'Information Technology': ['IT Policy & Infrastructure', 'Expenditure Details', 'Policy & Service Rules'],\n",
    "}\n",
    "\n",
    "print(\"Department config loaded —\", len(departments), \"departments,\",\n",
    "      sum(len(v) for v in dept_category_map.values()), \"total categories\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "347717c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ── Other distributions ────────────────────────────────────────\n",
    "applicant_types = {\n",
    "    'Individual Citizen': 0.62, 'Journalist / Media': 0.10,\n",
    "    'Lawyer / Legal Entity': 0.11, 'NGO / Civil Society': 0.09, 'Business Entity': 0.08,\n",
    "}\n",
    "\n",
    "states = {\n",
    "    'Maharashtra': 0.22, 'Gujarat': 0.10, 'Andhra Pradesh': 0.09,\n",
    "    'Telangana': 0.08, 'Delhi': 0.09, 'Karnataka': 0.06,\n",
    "    'Uttar Pradesh': 0.07, 'Tamil Nadu': 0.05, 'Rajasthan': 0.04,\n",
    "    'West Bengal': 0.04, 'Punjab': 0.03, 'Haryana': 0.03,\n",
    "    'Madhya Pradesh': 0.03, 'Odisha': 0.03, 'Kerala': 0.02,\n",
    "    'Bihar': 0.02, 'Others': 0.02, 'Jharkhand': 0.01,\n",
    "    'Himachal Pradesh': 0.01, 'Assam': 0.01,\n",
    "}\n",
    "\n",
    "disposal_types = {\n",
    "    'Information Provided': 0.52, 'Partially Provided': 0.20,\n",
    "    'Rejected': 0.15, 'Transferred to Concerned Department': 0.13,\n",
    "}\n",
    "\n",
    "rejection_reasons = {\n",
    "    'Section 8(1)(j) – Personal/Private Information': 0.33,\n",
    "    'Section 8(1)(d) – Commercial Confidence / IP': 0.24,\n",
    "    'Section 8(1)(e) – Fiduciary Relationship': 0.18,\n",
    "    'Section 8(1)(h) – Impede Investigation/Prosecution': 0.12,\n",
    "    'Section 8(1)(a) – National Security & Sovereignty': 0.07,\n",
    "    'Section 24 – Intelligence/Security Organisation': 0.06,\n",
    "}\n",
    "\n",
    "first_appeal_outcomes  = {'Upheld': 0.20, 'Partially Upheld': 0.30, 'Rejected': 0.50}\n",
    "second_appeal_outcomes = {'Upheld by CIC': 0.25, 'Partially Upheld by CIC': 0.30, 'Rejected by CIC': 0.45}\n",
    "pios = [f'PIO-{str(i).zfill(3)}' for i in range(1, 14)]\n",
    "\n",
    "# Year-wise volume — realistic growth with COVID dip (2020)\n",
    "year_volumes = {\n",
    "    2014: 430, 2015: 462, 2016: 495, 2017: 523, 2018: 548,\n",
    "    2019: 578, 2020: 485, 2021: 545, 2022: 622, 2023: 678, 2024: 714,\n",
    "}\n",
    "\n",
    "# Monthly seasonality — March & October are peaks (year-end / post-AGM)\n",
    "monthly_weights = [1.15, 0.85, 1.25, 0.90, 0.85, 0.78, 0.78, 0.88, 0.95, 1.20, 1.00, 1.02]\n",
    "\n",
    "# Delay multiplier per department (Vigilance = slowest; IT = fastest)\n",
    "dept_delay_factor = {\n",
    "    'HR & Personnel': 1.12, 'LPG Division (Indane)': 0.95,\n",
    "    'Finance & Accounts': 1.02, 'Retail Marketing': 0.95,\n",
    "    'Procurement & Materials': 1.10, 'Projects & Pipelines': 1.22,\n",
    "    'Mumbai Refinery': 1.18, 'Vizag Refinery': 1.18,\n",
    "    'Health, Safety & Environment': 1.00, 'Vigilance': 1.45,\n",
    "    'Legal & Secretarial': 1.12, 'Corporate Planning & BD': 0.90,\n",
    "    'Information Technology': 0.85,\n",
    "}\n",
    "\n",
    "print(\"All distributions configured.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "afac297f",
   "metadata": {},
   "source": [
    "## 3. Helper Functions"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92bae6f3",
   "metadata": {},
   "outputs": [],
   "source": [
    "def weighted_choice(d):\n",
    "    \"\"\"Choose a key from dict d using values as weights.\"\"\"\n",
    "    return random.choices(list(d.keys()), weights=list(d.values()), k=1)[0]\n",
    "\n",
    "def generate_filing_date(year):\n",
    "    \"\"\"Return a datetime for the given year, weighted by seasonal monthly pattern.\"\"\"\n",
    "    mw = monthly_weights.copy()\n",
    "    if year == 2024:\n",
    "        mw[9:] = [0, 0, 0]   # data only up to Sep 2024\n",
    "    month    = random.choices(range(1, 13), weights=mw, k=1)[0]\n",
    "    max_day  = [31, 29 if year % 4 == 0 else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month-1]\n",
    "    return datetime(year, month, random.randint(1, max_day))\n",
    "\n",
    "def get_quarter(month):\n",
    "    return f'Q{(month - 1) // 3 + 1}'\n",
    "\n",
    "print(\"Helper functions defined.\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "3b3bf656",
   "metadata": {},
   "source": [
    "## 4. Dataset Generation Loop\n",
    "Each record is generated with:\n",
    "- Correlated department → category selection\n",
    "- Year-adjusted online filing probability (digital adoption trend)\n",
    "- Department-specific response time distribution\n",
    "- COVID-year delay multiplier for 2020\n",
    "- Appeal probabilities conditioned on disposal type"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7a760476",
   "metadata": {},
   "outputs": [],
   "source": [
    "records, rti_counter = [], 1\n",
    "\n",
    "for year, volume in year_volumes.items():\n",
    "    for _ in range(volume):\n",
    "        filing_date    = generate_filing_date(year)\n",
    "        dept           = weighted_choice(departments)\n",
    "        category       = random.choice(dept_category_map[dept])\n",
    "        applicant_type = weighted_choice(applicant_types)\n",
    "        state          = weighted_choice(states)\n",
    "\n",
    "        # Online adoption grows year-on-year (25% in 2014 → ~52% in 2024)\n",
    "        online_w  = min(0.28 + (year - 2014) * 0.025, 0.70)\n",
    "        offline_w = (1 - online_w) * 0.55\n",
    "        post_w    = (1 - online_w) * 0.45\n",
    "        mode = random.choices(\n",
    "            ['Online (RTI Online Portal)', 'Offline (In-Person)', 'By Post'],\n",
    "            weights=[online_w, offline_w, post_w], k=1)[0]\n",
    "\n",
    "        pio = random.choice(pios)\n",
    "\n",
    "        # Response time: normal dist, department-adjusted, COVID-inflated for 2020\n",
    "        delay_factor  = dept_delay_factor.get(dept, 1.0)\n",
    "        if year == 2020:\n",
    "            delay_factor *= 1.30\n",
    "        response_days = max(5, int(np.random.normal(21, 8) * delay_factor))\n",
    "        response_date = filing_date + timedelta(days=response_days)\n",
    "\n",
    "        if response_days <= 30:   response_status = 'Responded On-Time'\n",
    "        elif response_days <= 60: response_status = 'Responded – Delayed (31–60 days)'\n",
    "        else:                     response_status = 'Responded – Significantly Delayed (>60 days)'\n",
    "\n",
    "        if year == 2024 and random.random() < 0.04:\n",
    "            response_status, response_date, response_days = 'Pending', None, None\n",
    "\n",
    "        disposal         = weighted_choice(disposal_types)\n",
    "        rejection_reason = weighted_choice(rejection_reasons) if disposal == 'Rejected' else None\n",
    "\n",
    "        # Appeal probability conditioned on disposal outcome\n",
    "        fa_prob = 0.07\n",
    "        if disposal == 'Rejected':           fa_prob = 0.45\n",
    "        elif disposal == 'Partially Provided': fa_prob = 0.22\n",
    "\n",
    "        first_appeal, fa_date, fa_outcome = 'No', None, None\n",
    "        second_appeal, sa_outcome         = 'No', None\n",
    "\n",
    "        if random.random() < fa_prob:\n",
    "            first_appeal = 'Yes'\n",
    "            ref          = response_date if response_date else filing_date + timedelta(days=30)\n",
    "            fa_date      = ref + timedelta(days=random.randint(10, 55))\n",
    "            fa_outcome   = weighted_choice(first_appeal_outcomes)\n",
    "            if fa_outcome == 'Rejected' and random.random() < 0.28:\n",
    "                second_appeal = 'Yes'\n",
    "                sa_outcome    = weighted_choice(second_appeal_outcomes)\n",
    "\n",
    "        records.append({\n",
    "            'RTI_ID':                f'HPCL-RTI-{str(rti_counter).zfill(5)}',\n",
    "            'Filing_Date':           filing_date.strftime('%Y-%m-%d'),\n",
    "            'Year':                  year,\n",
    "            'Month':                 filing_date.month,\n",
    "            'Month_Name':            filing_date.strftime('%B'),\n",
    "            'Quarter':               get_quarter(filing_date.month),\n",
    "            'Department':            dept,\n",
    "            'Category':              category,\n",
    "            'Applicant_Type':        applicant_type,\n",
    "            'State':                 state,\n",
    "            'Mode_of_Filing':        mode,\n",
    "            'PIO_Assigned':          pio,\n",
    "            'Response_Date':         response_date.strftime('%Y-%m-%d') if response_date else None,\n",
    "            'Response_Time_Days':    response_days,\n",
    "            'Response_Status':       response_status,\n",
    "            'Disposal_Type':         disposal,\n",
    "            'Rejection_Reason':      rejection_reason,\n",
    "            'First_Appeal_Filed':    first_appeal,\n",
    "            'First_Appeal_Date':     fa_date.strftime('%Y-%m-%d') if fa_date else None,\n",
    "            'First_Appeal_Outcome':  fa_outcome,\n",
    "            'Second_Appeal_CIC':     second_appeal,\n",
    "            'Second_Appeal_Outcome': sa_outcome,\n",
    "            'Is_Repeat_Filer':       'Yes' if random.random() < 0.18 else 'No',\n",
    "        })\n",
    "        rti_counter += 1\n",
    "\n",
    "df_raw = pd.DataFrame(records)\n",
    "print(f\"Dataset generated: {len(df_raw):,} records × {len(df_raw.columns)} columns\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e4c1c755",
   "metadata": {},
   "source": [
    "## 5. Dataset Preview & Summary"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ec5c5c77",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_raw.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2059cf96",
   "metadata": {},
   "outputs": [],
   "source": [
    "print(\"Shape:\", df_raw.shape)\n",
    "print(\"\\nYear-wise Volume:\")\n",
    "print(df_raw.groupby('Year').size().to_string())\n",
    "print(\"\\nDepartment Distribution:\")\n",
    "print(df_raw['Department'].value_counts().to_string())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b88cfff8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save raw dataset\n",
    "import os\n",
    "os.makedirs('../data/raw', exist_ok=True)\n",
    "df_raw.to_csv('../data/raw/hpcl_rti_2014_2024.csv', index=False)\n",
    "print(\"Saved: ../data/raw/hpcl_rti_2014_2024.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36e9e68f",
   "metadata": {},
   "source": [
    "---\n",
    "## Summary\n",
    "The generated dataset contains **6,080 RTI records** across 11 years with:\n",
    "- **13 HPCL departments** with realistic filing shares\n",
    "- **Seasonal trends** — March & October peak months\n",
    "- **COVID-19 impact** — 2020 shows volume dip and compliance drop\n",
    "- **Digital adoption** — Online filing grows from 25% (2014) to 52% (2024)\n",
    "- **Correlated fields** — Department → Category, Disposal → Appeal probability\n",
    "\n",
    "**Next:** Proceed to `02_data_cleaning_eda.ipynb` for cleaning, feature engineering, and full analysis."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
